In [13]:
import pandas as pd
from trial import get_columns_by_type
from preprocessing import (
    percentage_to_int, 
    join_and_sort, 
    set_indexes, 
    create_cleaned_df, 
    extract_ratio_features, 
    get_stats, 
    get_stats_windows,
    get_distance_traveled
)

In [2]:
conn = f"sqlite:///../db.sqlite3"
venues_df = pd.read_sql("SELECT * FROM venue", conn)
stats_df = pd.read_sql("SELECT * FROM statistic", conn)
fix_df = pd.read_sql("SELECT * FROM annotated_fixture", conn)

In [3]:
set_indexes(stats_df, fix_df)

In [4]:
df = join_and_sort(stats_df, fix_df)

In [6]:
extract_ratio_features(df)

/Users/robertcampbell/sqlalchemy-tutorial/ml/preprocessing.py:218: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe['accurate_passes'].replace(0, np.nan, inplace=True)
/Users/robertcampbell/sqlalchemy-tutorial/ml/preprocessing.py:218: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataframe['accurate_passes'].replace(0, np.nan, inplace=True)
/Users/robertcampbell/sqlalchemy-tutorial/ml/preprocessing.py:219: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe['total_passes'].replace(0, np.nan, inplace=True)

In [7]:
STATS_WINDOWS = get_stats_windows(df, 38)

In [14]:
STATS_WINDOWS

                                            mean_rating  min_rating  \
fixture_id team_id substitute away_team_id
65         33      0          46                    NaN         NaN
                              46                    NaN         NaN
                              46                    NaN         NaN
                              46                    NaN         NaN
                              46                    NaN         NaN
...                                                 ...         ...
868325     41      1          40                  6.725         6.3
                              40                  6.760         6.3
                              40                  6.760         6.3
                              40                  6.760         6.3
                              40                  6.760         6.3

                                            max_rating  std_rating  \
fixture_id team_id substitute away_team_id
65         33      0          46                   NaN         NaN
                              46                   NaN         NaN
                              46                   NaN         NaN
                              46                   NaN         NaN
                              46                   NaN         NaN
...                                                ...         ...
868325     41      1          40                   7.2    0.403113
                              40                   7.2    0.357771
                              40                   7.2    0.357771
                              40                   7.2    0.357771
                              40                   7.2    0.357771

                                            mean_tackles  min_tackles  \
fixture_id team_id substitute away_team_id
65         33      0          46                     NaN          NaN
                              46                2.000000          2.0
                              46                2.000000          2.0
                              46                2.333333          2.0
                              46                2.000000          1.0
...                                                  ...          ...
868325     41      1          40                1.000000          1.0
                              40                1.000000          1.0
                              40                1.000000          1.0
                              40                1.000000          1.0
                              40                1.000000          1.0

                                            max_tackles  std_tackles  \
fixture_id team_id substitute away_team_id
65         33      0          46                    NaN          NaN
                              46                    2.0          NaN
                              46                    2.0     0.000000
                              46                    3.0     0.577350
                              46                    3.0     0.816497
...                                                 ...          ...
868325     41      1          40                    1.0     0.000000
                              40                    1.0     0.000000
                              40                    1.0     0.000000
                              40                    1.0     0.000000
                              40                    1.0     0.000000

                                            mean_blocks  min_blocks  ...  \
fixture_id team_id substitute away_team_id                           ...
65         33      0          46                    NaN         NaN  ...
                              46                    0.0         0.0  ...
                              46                    0.0         0.0  ...
                              46                    0.0         0.0  ...
                              46                    0.0         0.0  ...
...                                                 ...         ...  ...
868325     41      1          40                    NaN         NaN  ...
                              40                    NaN         NaN  ...
                              40                    NaN         NaN  ...
                              40                    NaN         NaN  ...
                              40                    NaN         NaN  ...

                                            max_key_passes  std_key_passes  \
fixture_id team_id substitute away_team_id
65         33      0          46                       NaN             NaN
                              46                       0.0             NaN
                              46                       4.0        2.828427
                              46                       4.0        2.309401
                              46                       4.0        1.914854
...                                                    ...             ...
868325     41      1          40                       1.0             NaN
                              40                       1.0        0.000000
                              40                       1.0        0.000000
                              40                       1.0        0.000000
                              40                       1.0        0.000000

                                            mean_fouls_drawn  min_fouls_drawn  \
fixture_id team_id substitute away_team_id
65         33      0          46                         NaN              NaN
                              46                    0.000000              0.0
                              46                    1.500000              0.0
                              46                    1.333333              0.0
                              46                    1.000000              0.0
...                                                      ...              ...
868325     41      1          40                    1.000000              1.0
                              40                    1.000000              1.0
                              40                    1.000000              1.0
                              40                    1.000000              1.0
                              40                    1.000000              1.0

                                            max_fouls_drawn  std_fouls_drawn  \
fixture_id team_id substitute away_team_id
65         33      0          46                        NaN              NaN
                              46                        0.0              NaN
                              46                        3.0         2.121320
                              46                        3.0         1.527525
                              46                        3.0         1.414214
...                                                     ...              ...
868325     41      1          40                        1.0              NaN
                              40                        1.0              NaN
                              40                        1.0              NaN
                              40                        1.0              NaN
                              40                        1.0              NaN

                                            mean_fouls_committed  \
fixture_id team_id substitute away_team_id
65         33      0          46                             NaN
                              46                        0.000000
                              46                        0.500000
                              46                        0.333333
                              46                        0.250000
...                                                          ...
868325     41      1          40                             NaN
                              40                             NaN
                              40                             NaN
                              40                             NaN
                              40                             NaN

                                            min_fouls_committed  \
fixture_id team_id substitute away_team_id
65         33      0          46                            NaN
                              46                            0.0
                              46                            0.0
                              46                            0.0
                              46                            0.0
...                                                         ...
868325     41      1          40                            NaN
                              40                            NaN
                              40                            NaN
                              40                            NaN
                              40                            NaN

                                            max_fouls_committed  \
fixture_id team_id substitute away_team_id
65         33      0          46                            NaN
                              46                            0.0
                              46                            1.0
                              46                            1.0
                              46                            1.0
...                                                         ...
868325     41      1          40                            NaN
                              40                            NaN
                              40                            NaN
                              40                            NaN
                              40                            NaN

                                            std_fouls_committed
fixture_id team_id substitute away_team_id
65         33      0          46                            NaN
                              46                            NaN
                              46                       0.707107
                              46                       0.577350
                              46                       0.500000
...                                                         ...
868325     41      1          40                            NaN
                              40                            NaN
                              40                            NaN
                              40                            NaN
                              40                            NaN

[97530 rows x 40 columns]

In [8]:
CLEAN_DF = create_cleaned_df(df)

In [9]:
CLEAN_DF

,home_team_id,id_clean,team_id,player_id,minutes,rating,substitute,position,goals_total,goals_conceded,...,address,city,capacity,name_away,address_away,city_away,capacity_away,dribble_success_percentage,duels_won_percentage,passing_accuracy
fixture_id,,,,,,,,,,,,,,,,,,,,,
192904,49,97473,50,105426,13.0,NaN,0,M,NaN,NaN,...,Fulham Road,London,41841,Etihad Stadium,Rowsley Street,Manchester,55097,NaN,0.500,6.636
192905,42,97483,42,18769,70.0,NaN,0,M,1.0,NaN,...,Queensland Road,London,60383,Villa Park,Trinity Road,Birmingham,42788,0.333,0.400,5.867
192966,76,97530,40,105422,26.0,NaN,0,M,NaN,NaN,...,Normandy Road,Swansea,21028,Anfield,Anfield Road,Liverpool,55212,NaN,1.000,4.524
192297,33,87024,47,170,90.0,NaN,0,D,NaN,0.0,...,Sir Matt Busby Way,Manchester,76212,Tottenham Hotspur Stadium,"Bill Nicholson Way, 748 High Road",London,62850,NaN,0.500,1.661
192300,46,87111,746,114744,90.0,NaN,0,M,NaN,0.0,...,Filbert Way,"Leicester, Leicestershire",34310,NaN,NaN,NaN,NaN,0.667,0.667,2.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
868325,41,15159,41,303460,12.0,6.3,1,F,NaN,0.0,...,Britannia Road,"Southampton, Hampshire",32689,Anfield,Anfield Road,Liverpool,55212,NaN,0.167,0.500
868317,66,14855,51,26475,89.0,7.2,0,F,1.0,0.0,...,Trinity Road,Birmingham,42788,The American Express Community Stadium,Village Way,"Falmer, East Sussex",31872,1.000,0.429,0.737
868318,55,14880,55,15745,1.0,NaN,1,D,NaN,0.0,...,"166 Lionel Rd N, Brentford","Brentford, Middlesex",17250,Etihad Stadium,Rowsley Street,Manchester,55097,NaN,NaN,0.250
868316,42,14805,42,284540,NaN,NaN,1,M,NaN,0.0,...,Queensland Road,London,60383,Molineux Stadium,Waterloo Road,"Wolverhampton, West Midlands",34624,NaN,NaN,NaN
868319,49,14945,34,18892,NaN,NaN,1,D,NaN,0.0,...,Fulham Road,London,41841,St. James' Park,St. James&apos; Street,Newcastle upon Tyne,52758,NaN,NaN,NaN

In [ ]:
get_distance_traveled()